name: accounts

partition_by: 
  - __data_as_of_date

source:
  file_path_glob_pattern: "DD_account_table_*.txt"
  delimiter: "\t"
  encoding: "latin-1"
  quoting: 1
  quote_char: '"'

columns:
  account_number:
    csv_header: "Account Number"

  client_code:
    csv_header: "Client Code"
    
  ia_code:
    csv_header: "IA (Account)"
  
  sub_type:
    csv_header: "Account Sub Type"
  
  residence_code:
    csv_header: "Residence (Account)"

  status:
    csv_header: "Status (Account)"
  
  short_name:
    csv_header: "Short Name (Account)"

  is_allowed_to_trade:
    csv_header: "Trades OK"
    
  opened_date:
    csv_header: "Open Date (Account)"

  closed_date:
    csv_header: "Close Date (Account)"

  closed_reason:
    csv_header: "Reason"

  last_activity_date:
    csv_header: "Last Activity Date"

  last_trade_date:
    csv_header: "Last Trade Date"

  account_type:
    csv_header: "Account Type"

  portfolio_type_code:
    csv_header: "Portfolio Type"

  class_code:
    csv_header: "Class (Account)"

  minimum_commission_check:
    csv_header: "Minimum Commission?"

  commission_type_code:
    csv_header: "Type of Commission"

  credit_interest_code:
    csv_header: "Credit Int"

  debit_interest_code:
    csv_header: "Debit Int"

  is_discretionary:
    csv_header: "Discretionary"

  open_items:
    csv_header: "Open Item"

  option_approval_level_code:
    csv_header: "Option Approval"

  consolidation_level:
    csv_header: "Consolidation Level"
  
  currency:
    csv_header: "Funds (Account)"

  market_value_amount:
    csv_header: "Market Value (Account)"
  
  equity_amount:
    csv_header: "Equity/RTS (Account)"
  
  loan_value_amount:
    csv_header: "Loan Value (Account)"

  buying_power_amount:
    csv_header: "Buy Pwr/RTM (Account)"

  settlement_date_cash_balance:
    csv_header: "S/D Balance (Account)"

  trade_date_cash_balance:
    csv_header: "T/D Balance (Account)"

  crm2_inception_date:
    csv_header: "CRM2 Inception Date"

  crm2_eligibility_flag:
    csv_header: "CRM2 Eligibility Flag"

  inception_date_override:
    csv_header: "Inception Date Override"

  use_spouses_birthdate:
    csv_header: "RRIF Birthdate"
    
  # # 2 digit date
  # last_date:
  #   csv_header: "Last Date"
  #   type_caster:
  #     output_type: date
  #     interpret_mode: prefer_past
  
  last_interest_date:
    csv_header: "last Interest"
  
  last_roi_date:
    csv_header: "Last ROI Date"
  
  last_statement_date:
    csv_header: "Last Statement"
  
  last_seg_date:
    csv_header: "Last Seg Dt"
    
  check_credit:
    csv_header: "Check Credit"
  





    

