
name: insider_records

loading_strategy: snapshot

source:
  file_path_glob_pattern: "DD_insider_table_*.txt"
  delimiter: "\t"
  encoding: "latin-1"
  quoting: 1
  quote_char: '"'

# table_schema:
#   business_key: [client_code, cusip]

  # foreign_keys:
  #   - local_columns: [client_code]
  #     remote_table: client
  #     remote_columns: [client_code]
    
columns:
  client_code:
    csv_header: "Client Code"
    type_caster:
      output_type: integer
  
  cusip:
    csv_header: "Cusip"
  
  relationship_code:
    csv_header: "Relationship Code"
  
  creation_date:
    csv_header: "Creation Date"
    type_caster:
      output_type: date
      interpret_mode: "prefer_past"