name: securities

source:
  file_path_glob_pattern: "DD_security_table_*.txt"
  delimiter: "\t"
  encoding: "latin"
  quoting: 1
  quote_char: '"'

columns:
  cusip:
    csv_header: 
      - "Cusip/Security (Position)"
      - "Cusip/Security (Trans)"
      - "Cusip"

  security_class_code:
    csv_header: "Security Class"

  isin:
    csv_header: "ISIN"

  security_name:
    csv_header: "Name"

  status:
    csv_header: "Status (Securities)"

  market:
    csv_header: "Market"

  primary_symbol:
    csv_header: "Primary Symbol"

  is_able_to_trade:
    csv_header: "Trades OK"

  currency:
    csv_header: "Funds"

  strike_price:
    csv_header: "Strike Price"

  ask_price:
    csv_header: "Ask"

  bid_price:
    csv_header: "Bid"

  last_trade_price:
    csv_header: "Last Trade"

  loan_value_long_1:
    csv_header: "Firm LV-Long 1"

  loan_value_long_2:
    csv_header: "Firm LV-Long 2"

  loan_value_long_3:
    csv_header: "Firm LV-Long 3"

  loan_value_short_1:
    csv_header: "Firm LV-Short 1"

  loan_value_short_2:
    csv_header: "Firm LV-Short 2"

  loan_value_short_3:
    csv_header: "Firm LV-Short 3"

  decimals:
    csv_header: "Decimals"

  price_source:
    csv_header: "Price Source"

  price_factor:
    csv_header: "Price Factor"

  price_status_code:
    csv_header: "Price Status"

  has_manual_price:
    csv_header: "Manual Price"

  incorporation_country_code:
    csv_header: "Incorporation Country"

  is_us_eci:
    csv_header: "US ECI\u00a0"

  portfolio_class:
    csv_header: "Portfolio Class"

  call_put_indicator:
    csv_header: "Call/Put"

  underlying_symbol:
    csv_header: "Undr Symbol"

  underlying_cusip:
    csv_header: "Under CUSIP"

  expiry_date:
    csv_header: "Expiry Date"

  code:
    csv_header: "Security Code"

  gics_sub_industry:
    csv_header: "GICS Sub-industry"

  category:
    csv_header: "Category"

  has_reduced_margin:
    csv_header: "Reduced Margin"

  trades_options:
    csv_header: "Trades Options"

  is_convertible:
    csv_header: "Convertible"

  is_cds_eligible:
    csv_header: "CDS Elig?"

  cds_status:
    csv_header: "CDS Status"

  cds_subtype:
    csv_header: "CDS Subtype"

  comment:
    csv_header: "Security Comment"

  fund_class:
    csv_header: "Fund Class"

  product:
    csv_header: "Product"

  registered_doc:
    csv_header: "Registered Doc"